name: Pipeline CI/CD

on:
  push:
    branches:
      - feature-1

# DEFINIMOS VARIABLES DE ENTORNO
env:
  REPO_NAME: DevSecOps-Laboratorio-Final
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  organizacion: devsecops-laboratoriofinal

jobs:
  SAST:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. Instalar jq
      #- name: Install jq
      #  run: sudo apt-get update && sudo apt-get install -y jq

      # 2. Configurar Node.js
      #- name: Set up Node.js
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: 17 # Ajusta según la versión usada en tu proyecto

      # 3. Instalar dependencias del proyecto
      #- name: Install Dependencies
      #  run: npm install

      # 4. Verificar y crear proyecto en SonarCloud si no existe
      - name: Check and Create Project on SonarCloud
        id: validateProjectOnSonar
        run: |
          echo "Buscando proyecto en SonarCloud..."
          
          # Buscar el proyecto en SonarCloud
          RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME&organization=$organizacion")

          echo "Response: $RESPONSE"

          # Verificar si la respuesta contiene datos válidos
          EXISTING_PROJECT=$(echo "$RESPONSE" | jq '.paging.total' 2>/dev/null)

          if [ "$EXISTING_PROJECT" == "1" ]; then
            echo "El proyecto ya existe"
          elif [ "$EXISTING_PROJECT" == "null" ]; then
            echo "Error al obtener datos de la API de SonarCloud."
            exit 1
          else
            echo "Proyecto no existe... Creando proyecto en SonarCloud..."
            CREATE_RESPONSE=$(curl -s -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
              "https://sonarcloud.io/api/projects/create" \
              -d "name=$REPO_NAME" \
              -d "project=$REPO_NAME" \
              -d "organization=$organizacion" \
              -d "visibility=public")
            
            # Verificar si la creación fue exitosa
            if echo "$CREATE_RESPONSE" | jq -e '.errors' > /dev/null; then
              echo "Fallo la creación del proyecto en SonarCloud"
              exit 1
            else
              echo "Proyecto $REPO_NAME creado exitosamente en SonarCloud"
            fi
          fi
